print(123)
print(456)
a = input("Юра лох?")
if a == 'да':
    print('Молодец, верно!')
else:
    print('Не верно')
a = int(input())
b = int(input())
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** b)
print(a // b)
